// Jobs Radar — fake data
// 1 line = 1 offer. 24 offers (realistic daily load 15-40 new).
// Mix of scores to drive hero + list layout.

window.JOBS_DATA = {
  // Scan meta — today
  scan: {
    date_label: "Lundi 20 avril",
    raw_count: 142,
    processed_count: 28,
    hot_leads_count: 3,
    // 7-day rolling volumes
    tendances: {
      volumes_7d: [18, 24, 19, 31, 22, 15, 28], // lun→dim
      ratios_sector: [
        { label: "Scale-up B/C", pct: 38 },
        { label: "Grand groupe", pct: 24 },
        { label: "Série A", pct: 20 },
        { label: "Seed", pct: 12 },
        { label: "Scale", pct: 6 },
      ],
      ratios_category: [
        { id: "produit", label: "Produit", pct: 42 },
        { id: "rte",     label: "RTE",     pct: 18 },
        { id: "pgm",     label: "PgM",     pct: 22 },
        { id: "pjm",     label: "PjM",     pct: 12 },
        { id: "cos",     label: "CoS",     pct: 6  },
      ],
    },
    signal_cv: {
      // Rolling 30d — which CV format recommended more often
      pdf_pct: 64,
      docx_pct: 36,
      window_days: 30,
      insight: "Les 10 dernières hot leads ont toutes recommandé le PDF — garde la version design à jour.",
    },
    actions: [
      { id: "a1", kind: "apply", label: "Relancer Aircall — applied il y a 12 jours, pas de réponse", cta: "Relancer" },
      { id: "a2", kind: "prep",  label: "Préparer l'entretien Doctolib — jeudi 14h", cta: "Ouvrir le dossier" },
    ],
  },

  // Category & stage taxonomy
  categories: [
    { id: "produit", label: "Produit" },
    { id: "rte",     label: "RTE" },
    { id: "pgm",     label: "Program Manager" },
    { id: "pjm",     label: "Project Manager" },
    { id: "cos",     label: "Chief of Staff" },
  ],
  stages: [
    { id: "seed",          label: "Seed" },
    { id: "A",             label: "Série A" },
    { id: "B",             label: "Série B" },
    { id: "C",             label: "Série C" },
    { id: "scale",         label: "Scale-up" },
    { id: "grand_groupe",  label: "Grand groupe" },
  ],

  offers: [
    // ═══════════ HOT LEADS (score ≥ 7) ═══════════
    {
      id: "j01",
      title: "Head of Product — Plateforme data",
      company: "Alan",
      url: "https://linkedin.com/jobs/view/alan-head-product",
      posted_days_ago: 1,
      role_category: "produit",
      company_stage: "scale",
      pitch: "Piloter la plateforme data qui sous-tend l'expérience adhérent. Équipe de 8 PM, rattachement CPO, fort scope tech.",
      compensation: "110-140k€ + BSPCE",
      score_total: 9.2,
      score_seniority: 3,
      score_sector: 3,
      score_impact: 3.2,
      score_bonus: 1,
      rubric_justif: [
        { axis: "Séniorité", text: "Head of avec 8 PM sous la main — scope exact que tu vises depuis 6 mois." },
        { axis: "Secteur",   text: "Assurtech scale-up rentable, exactement la maturité qui t'intéresse." },
        { axis: "Impact",    text: "Plateforme data transverse — levier produit énorme, CPO accessible." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Boîte design-forward, le PDF mis en forme passe mieux que le docx ATS.",
      intel: {
        company_signals: [
          "Levée série E 183M$ en mars 2026 — runway 24 mois confirmé",
          "Recrutement accéléré produit : 3 postes PM ouverts + 1 Head of",
          "Pivot récent vers les TPE (entreprises <10 salariés)",
        ],
        lead: {
          name: "Marion Dufresne",
          role: "CPO",
          linkedin: "https://linkedin.com/in/marion-dufresne",
          notes: "Ex-Doctolib (2019-2023), passée par Back Market. Active sur LinkedIn, parle publiquement de plateforme data.",
        },
        safe_maturity: null,
        warm_network: [
          { name: "Sophie Bénézit", degree: 1, relation: "Ancienne collègue BNP — maintenant Sr PM chez Alan" },
          { name: "Thomas Rey",     degree: 2, relation: "Via Sophie, dans l'équipe data" },
        ],
        angle: "Mentionne la pivot TPE et ta lecture du dernier post LinkedIn de Marion sur les plateformes internes. Demande à Sophie un warm intro plutôt qu'une candid spontanée — elle va recommander.",
      },
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
      user_notes: "",
    },
    {
      id: "j02",
      title: "Release Train Engineer — Core Banking",
      company: "Qonto",
      url: "https://linkedin.com/jobs/view/qonto-rte",
      posted_days_ago: 2,
      role_category: "rte",
      company_stage: "scale",
      pitch: "Piloter un ART de 60 personnes sur les flux de paiement. SAFe 6.0 déployé depuis 18 mois, train mature.",
      compensation: "95-115k€",
      score_total: 8.6,
      score_seniority: 3,
      score_sector: 2.6,
      score_impact: 3,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "RTE sur un ART mature — tu as déjà fait ça à la BNP, scope comparable." },
        { axis: "Secteur",   text: "Fintech B2B, proche de ton domaine actuel. Pas une vraie rupture." },
        { axis: "Impact",    text: "60 personnes, flux paiement — cœur métier, forte visibilité COMEX." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Recrutement tech-first — PDF mis en forme avec focus SAFe et métriques.",
      intel: {
        company_signals: [
          "Levée 552M€ en 2022 — profitabilité visée 2026",
          "Restructuration produit mars 2026 : 3 ARTs devenus 5",
          "RTE sortant a rejoint Swile (départ public sur LinkedIn)",
        ],
        lead: {
          name: "Julien Aubert",
          role: "VP Engineering",
          linkedin: "https://linkedin.com/in/julien-aubert-qonto",
          notes: "Ex-Criteo, sur le sujet SAFe depuis 4 ans. A publié un article sur le blog Qonto engineering.",
        },
        safe_maturity: "Mature (SAFe 6.0, 18 mois de train)",
        warm_network: [
          { name: "Paul Marchand", degree: 2, relation: "Via LinkedIn — Engineering Manager chez Qonto" },
        ],
        angle: "Référence la restructuration 3→5 ARTs comme hook : 'je vois que vous scalez le modèle, voici ce que j'ai appris en passant d'1 à 4 trains à la BNP'.",
      },
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
      user_notes: "",
    },
    {
      id: "j03",
      title: "Senior Product Manager — AI Agents",
      company: "Mistral AI",
      url: "https://linkedin.com/jobs/view/mistral-spm-agents",
      posted_days_ago: 1,
      role_category: "produit",
      company_stage: "C",
      pitch: "Définir la product vision sur le volet agents de la plateforme Le Chat Enterprise. Équipe de 4 PM.",
      compensation: "100-130k€ + equity",
      score_total: 7.8,
      score_seniority: 2.6,
      score_sector: 3,
      score_impact: 3.2,
      score_bonus: 1,
      rubric_justif: [
        { axis: "Séniorité", text: "Senior PM, pas Head of — un cran en-dessous de ton target, mais sur un sujet brûlant." },
        { axis: "Secteur",   text: "IA générative, scale-up française leader. Matchs parfait avec tes lectures." },
        { axis: "Impact",    text: "Agents = LE sujet 2026. Visibilité énorme, post-IPO possible 2027." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Profil tech-product — PDF qui met en avant tes projets IA à la BNP.",
      intel: {
        company_signals: [
          "Série C 600M€ bouclée en décembre 2025 — IPO projetée 2027",
          "Ouverture d'un bureau tech à Station F (40 postes)",
          "Partenariat annoncé avec Bpifrance pour l'ETI-tech",
        ],
        lead: {
          name: "Clara Vinson",
          role: "VP Product",
          linkedin: "https://linkedin.com/in/clara-vinson",
          notes: "Ex-Google DeepMind. Recrute activement, répond aux DMs LinkedIn sur les posts agents.",
        },
        safe_maturity: null,
        warm_network: [],
        angle: "Pas de warm intro. Va direct via Clara : mentionne un projet agent concret (pas une idée — un truc livré). Réfère au blog post Mistral sur les function-calling agents.",
      },
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
      user_notes: "",
    },

    // ═══════════ MID-SCORE (5 ≤ score < 7) ═══════════
    {
      id: "j04",
      title: "Lead Product Manager — Growth",
      company: "Swile",
      url: "https://linkedin.com/jobs/view/swile-lpm-growth",
      posted_days_ago: 3,
      role_category: "produit",
      company_stage: "C",
      pitch: "Piloter le squad growth, focus acquisition B2B. Rattachement CPO.",
      compensation: "90-110k€",
      score_total: 6.4,
      score_seniority: 2.4,
      score_sector: 2,
      score_impact: 2,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Lead PM — sous ton niveau de séniorité visé mais bon scope." },
        { axis: "Secteur",   text: "Food-tech B2B, pas ton univers de prédilection." },
        { axis: "Impact",    text: "Growth pur, KPI acquisition — impact mesurable mais scope étroit." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process ATS standard, le docx passe mieux.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j05",
      title: "Release Train Engineer",
      company: "BNP Paribas",
      url: "https://linkedin.com/jobs/view/bnp-rte-bddf",
      posted_days_ago: 2,
      role_category: "rte",
      company_stage: "grand_groupe",
      pitch: "Piloter un ART de 80 personnes sur la banque de détail France. SAFe 5.1, train stable.",
      compensation: "85-105k€",
      score_total: 6.2,
      score_seniority: 2.8,
      score_sector: 1.8,
      score_impact: 1.6,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Scope RTE mature — tu connais." },
        { axis: "Secteur",   text: "Ton employeur actuel (ou très proche) — pas un vrai move." },
        { axis: "Impact",    text: "ART sur le périmètre BDDF — scope visible mais cadre rigide." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process groupe, DOCX requis par le SIRH interne.",
      status: "archived",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j06",
      title: "Program Manager — Plateforme IA",
      company: "Doctolib",
      url: "https://linkedin.com/jobs/view/doctolib-pgm-ia",
      posted_days_ago: 4,
      role_category: "pgm",
      company_stage: "scale",
      pitch: "Piloter le programme IA santé (4 squads). Rattachement VP Engineering.",
      compensation: "100-120k€",
      score_total: 6.8,
      score_seniority: 2.6,
      score_sector: 2.4,
      score_impact: 1.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PgM avec 4 squads — dans ta zone de séniorité." },
        { axis: "Secteur",   text: "HealthTech scale-up française — intéressant, proche de ce que tu vises." },
        { axis: "Impact",    text: "Programme naissant, beaucoup à structurer — levier fort mais risque politique." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Doctolib est design-sensible, PDF valorise mieux.",
      status: "to_apply",
      first_seen_date: "2026-04-18",
      last_seen_date: "2026-04-20",
      user_notes: "Entretien jeudi 14h — Sophie me prépare un brief sur la politique interne.",
    },
    {
      id: "j07",
      title: "Senior Program Manager — Platform",
      company: "PayFit",
      url: "https://linkedin.com/jobs/view/payfit-pgm",
      posted_days_ago: 5,
      role_category: "pgm",
      company_stage: "C",
      pitch: "Structurer la gouvernance platform (3 squads). SAFe light en déploiement.",
      compensation: "85-110k€",
      score_total: 5.6,
      score_seniority: 2.2,
      score_sector: 1.8,
      score_impact: 1.6,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Senior PgM, 3 squads — un peu léger vs ton niveau." },
        { axis: "Secteur",   text: "RH-tech B2B, pas ton univers naturel." },
        { axis: "Impact",    text: "SAFe light en déploiement — scope structurant mais early stage." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Format standard, recrutement orienté produit.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j08",
      title: "Chief of Staff — Office CTO",
      company: "Ledger",
      url: "https://linkedin.com/jobs/view/ledger-cos",
      posted_days_ago: 6,
      role_category: "cos",
      company_stage: "C",
      pitch: "Bras droit du CTO sur les sujets tech-strat, OKRs, recrutement.",
      compensation: "90-120k€ + BSPCE",
      score_total: 6.0,
      score_seniority: 2.4,
      score_sector: 2,
      score_impact: 1.6,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "CoS office CTO — très politique, scope variable." },
        { axis: "Secteur",   text: "Crypto scale-up — sortir du cœur fintech classique." },
        { axis: "Impact",    text: "Scope transverse mais dépend beaucoup du CTO, risque volatilité." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Rôle sensible à la narration, PDF avec histoire claire.",
      status: "snoozed",
      first_seen_date: "2026-04-14",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j09",
      title: "Lead Product Manager — Fintech B2B",
      company: "Aircall",
      url: "https://linkedin.com/jobs/view/aircall-lpm-b2b",
      posted_days_ago: 14,
      role_category: "produit",
      company_stage: "C",
      pitch: "Lead PM sur le produit entreprise (>500 seats). Équipe de 3 PM.",
      compensation: "85-110k€",
      score_total: 6.2,
      score_seniority: 2.4,
      score_sector: 2,
      score_impact: 1.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Lead PM — un peu sous ta cible, mais scope entreprise solide." },
        { axis: "Secteur",   text: "SaaS télécom B2B — pas un secteur chaud pour toi." },
        { axis: "Impact",    text: "Segment entreprise = marge forte, mais cycle lent." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process ATS standard.",
      status: "applied",
      first_seen_date: "2026-04-06",
      last_seen_date: "2026-04-20",
      user_notes: "Postulé le 08/04 — pas de retour. À relancer (action auto suggérée).",
    },
    {
      id: "j10",
      title: "Group Product Manager — Observability",
      company: "Datadog",
      url: "https://linkedin.com/jobs/view/datadog-gpm",
      posted_days_ago: 3,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "GPM sur la suite observability, équipe Paris. 5 PM rattachés.",
      compensation: "130-160k€ + RSU",
      score_total: 5.8,
      score_seniority: 3,
      score_sector: 1.4,
      score_impact: 1.4,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "GPM — match parfait séniorité." },
        { axis: "Secteur",   text: "DevTools observability — pas ton univers, courbe d'apprentissage longue." },
        { axis: "Impact",    text: "Équipe distribuée, HQ NY — scope large mais décision lointaine." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Process US-style, PDF épuré.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j11",
      title: "Senior Project Manager — Transfo digitale",
      company: "Decathlon",
      url: "https://linkedin.com/jobs/view/decathlon-pjm",
      posted_days_ago: 2,
      role_category: "pjm",
      company_stage: "grand_groupe",
      pitch: "Piloter les projets de transfo sur le retail digital. Équipes France + intl.",
      compensation: "70-90k€",
      score_total: 5.0,
      score_seniority: 2,
      score_sector: 1.4,
      score_impact: 1.6,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PjM senior — sous ton niveau." },
        { axis: "Secteur",   text: "Retail grand groupe — pas ton secteur." },
        { axis: "Impact",    text: "Transfo digitale large mais scope projet, pas produit." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH interne Decathlon, DOCX requis.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j12",
      title: "Principal Product Manager — Data Platform",
      company: "Contentsquare",
      url: "https://linkedin.com/jobs/view/contentsquare-ppm",
      posted_days_ago: 4,
      role_category: "produit",
      company_stage: "C",
      pitch: "Principal PM sur la platform data interne. Équipe de 6 PM, rattachement CPO.",
      compensation: "110-140k€",
      score_total: 6.6,
      score_seniority: 2.8,
      score_sector: 2,
      score_impact: 1.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Principal PM — au-dessus de ton niveau actuel, stretch intéressant." },
        { axis: "Secteur",   text: "MarTech scale-up, secteur proche." },
        { axis: "Impact",    text: "Platform data — levier interne fort mais pas user-facing." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Process design-aware, PDF mis en forme.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j13",
      title: "Program Manager — Fintech",
      company: "Shift Technology",
      url: "https://linkedin.com/jobs/view/shift-pgm",
      posted_days_ago: 5,
      role_category: "pgm",
      company_stage: "C",
      pitch: "PgM sur le programme fraud detection. 3 squads IA.",
      compensation: "85-105k€",
      score_total: 5.4,
      score_seniority: 2,
      score_sector: 2,
      score_impact: 1.4,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PgM 3 squads — en ligne." },
        { axis: "Secteur",   text: "Insurtech IA — intéressant, sec fort." },
        { axis: "Impact",    text: "Scope fraud detection, périmètre technique." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Recrutement tech-first.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },

    // ═══════════ LOW-SCORE (< 5) ═══════════
    {
      id: "j14",
      title: "Product Manager",
      company: "Carrefour",
      url: "https://linkedin.com/jobs/view/carrefour-pm",
      posted_days_ago: 1,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "PM sur le volet fidélité mobile.",
      compensation: "60-75k€",
      score_total: 3.4,
      score_seniority: 1.2,
      score_sector: 1,
      score_impact: 1.2,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PM mid-level — très sous ta cible." },
        { axis: "Secteur",   text: "Retail grand groupe — out of scope." },
        { axis: "Impact",    text: "Scope fidélité mobile, impact limité." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH interne.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j15",
      title: "Chef de projet digital",
      company: "La Poste",
      url: "https://linkedin.com/jobs/view/laposte-cp",
      posted_days_ago: 2,
      role_category: "pjm",
      company_stage: "grand_groupe",
      pitch: "Piloter un projet de refonte de l'espace client.",
      compensation: "55-70k€",
      score_total: 2.8,
      score_seniority: 1,
      score_sector: 0.8,
      score_impact: 1,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Chef de projet — bien sous ta cible." },
        { axis: "Secteur",   text: "Grand groupe public, out of scope." },
        { axis: "Impact",    text: "Projet refonte, scope limité." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process public classique.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j16",
      title: "Senior PM — Mobile",
      company: "BlaBlaCar",
      url: "https://linkedin.com/jobs/view/blablacar-spm-mobile",
      posted_days_ago: 3,
      role_category: "produit",
      company_stage: "scale",
      pitch: "Senior PM sur les apps mobile iOS/Android, équipe de 8 devs.",
      compensation: "75-95k€",
      score_total: 4.8,
      score_seniority: 1.8,
      score_sector: 1.4,
      score_impact: 1.6,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Senior PM — sous ta cible." },
        { axis: "Secteur",   text: "Mobility scale-up, pas ton univers." },
        { axis: "Impact",    text: "Scope mobile spécifique, pas transverse." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Design-forward.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j17",
      title: "Product Owner — Moyens de paiement",
      company: "Société Générale",
      url: "https://linkedin.com/jobs/view/socgen-po",
      posted_days_ago: 2,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "PO sur le train paiement instantané.",
      compensation: "55-70k€",
      score_total: 2.6,
      score_seniority: 0.8,
      score_sector: 1,
      score_impact: 0.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PO — très sous ton niveau." },
        { axis: "Secteur",   text: "Banque classique — équivalent à ton poste actuel." },
        { axis: "Impact",    text: "Scope train spécifique." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH groupe bancaire.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j18",
      title: "Product Manager — Marketplace",
      company: "Back Market",
      url: "https://linkedin.com/jobs/view/backmarket-pm",
      posted_days_ago: 4,
      role_category: "produit",
      company_stage: "C",
      pitch: "PM sur le volet seller onboarding marketplace.",
      compensation: "75-90k€",
      score_total: 4.6,
      score_seniority: 1.6,
      score_sector: 1.6,
      score_impact: 1.4,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PM — sous ta cible." },
        { axis: "Secteur",   text: "Marketplace scale-up, intéressant mais scope limité." },
        { axis: "Impact",    text: "Seller onboarding, niche." },
      ],
      cv_recommended: "pdf",
      cv_reason: "Design-forward, PDF.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j19",
      title: "Lead PM — Checkout",
      company: "Veepee",
      url: "https://linkedin.com/jobs/view/veepee-lpm-checkout",
      posted_days_ago: 5,
      role_category: "produit",
      company_stage: "scale",
      pitch: "Lead PM sur le funnel checkout e-commerce.",
      compensation: "80-100k€",
      score_total: 4.4,
      score_seniority: 2,
      score_sector: 1.2,
      score_impact: 1.2,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Lead PM — un cran sous." },
        { axis: "Secteur",   text: "E-commerce classique, pas ton univers." },
        { axis: "Impact",    text: "Funnel checkout, scope étroit." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process ATS.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j20",
      title: "Project Manager — ERP Finance",
      company: "Veolia",
      url: "https://linkedin.com/jobs/view/veolia-pm-erp",
      posted_days_ago: 3,
      role_category: "pjm",
      company_stage: "grand_groupe",
      pitch: "Piloter le déploiement SAP du périmètre finance.",
      compensation: "65-85k€",
      score_total: 2.4,
      score_seniority: 1,
      score_sector: 0.6,
      score_impact: 0.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PjM mid — sous ta cible." },
        { axis: "Secteur",   text: "Utilities, out of scope total." },
        { axis: "Impact",    text: "Déploiement ERP, scope technique." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH grand groupe.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j21",
      title: "Product Manager — Énergie",
      company: "TotalEnergies",
      url: "https://linkedin.com/jobs/view/totalenergies-pm",
      posted_days_ago: 2,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "PM sur l'app mobile client B2C.",
      compensation: "60-80k€",
      score_total: 2.0,
      score_seniority: 0.8,
      score_sector: 0.4,
      score_impact: 0.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PM — sous ton niveau." },
        { axis: "Secteur",   text: "Énergie grand groupe — très loin." },
        { axis: "Impact",    text: "App mobile B2C, scope limité." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j22",
      title: "Product Owner — Data Platform",
      company: "Orange",
      url: "https://linkedin.com/jobs/view/orange-po-data",
      posted_days_ago: 4,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "PO sur la platform data interne groupe.",
      compensation: "60-75k€",
      score_total: 2.6,
      score_seniority: 1,
      score_sector: 0.8,
      score_impact: 0.8,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PO — sous ta cible." },
        { axis: "Secteur",   text: "Télécom grand groupe." },
        { axis: "Impact",    text: "Platform data interne." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j23",
      title: "Senior PjM — Digital Factory",
      company: "AXA",
      url: "https://linkedin.com/jobs/view/axa-spjm",
      posted_days_ago: 1,
      role_category: "pjm",
      company_stage: "grand_groupe",
      pitch: "Sr PjM sur la Digital Factory — 3 projets transverses.",
      compensation: "70-85k€",
      score_total: 4.2,
      score_seniority: 1.8,
      score_sector: 1.2,
      score_impact: 1.2,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "Senior PjM — sous ta cible." },
        { axis: "Secteur",   text: "Assurance grand groupe, proche de ton actuel." },
        { axis: "Impact",    text: "Digital Factory, scope projet." },
      ],
      cv_recommended: "docx",
      cv_reason: "SIRH.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
    {
      id: "j24",
      title: "Product Manager — Billing",
      company: "OVHcloud",
      url: "https://linkedin.com/jobs/view/ovh-pm-billing",
      posted_days_ago: 3,
      role_category: "produit",
      company_stage: "grand_groupe",
      pitch: "PM sur le moteur billing du cloud.",
      compensation: "65-85k€",
      score_total: 3.8,
      score_seniority: 1.4,
      score_sector: 1.2,
      score_impact: 1.2,
      score_bonus: 0,
      rubric_justif: [
        { axis: "Séniorité", text: "PM — sous ta cible." },
        { axis: "Secteur",   text: "Cloud infrastructure, pas ton univers." },
        { axis: "Impact",    text: "Billing — scope backend." },
      ],
      cv_recommended: "docx",
      cv_reason: "Process ATS.",
      status: "new",
      first_seen_date: "2026-04-20",
      last_seen_date: "2026-04-20",
    },
  ],
};
