// Actualités — France + international
window.NEWS_DATA = {
  headline: {
    kicker: "Économie · il y a 2h",
    actor: "BCE",
    version: "Décision taux avril 2026",
    tagline: "La BCE baisse ses taux de 25 points de base — 2e baisse consécutive",
    body: "Lagarde confirme le signal désinflationniste. Taux directeur à 2.50%. Première fois sous 3% depuis 2022. Le CAC 40 bondit de 1.8% à l'ouverture, le livret A pourrait baisser à 2.25% en août.",
    metrics: [
      { label: "Taux directeur", value: "2.50%", delta: "-0.25" },
      { label: "Inflation zone €", value: "2.1%", delta: "-0.3" },
      { label: "CAC 40", value: "8 420", delta: "+1.8%" },
      { label: "Livret A probable", value: "2.25%", delta: "-0.25" },
    ],
    tags: ["#bce", "#taux", "#economie", "#france"],
  },

  actors: [
    { id: "bce", name: "BCE", mark: "€", color: "#003399", followed: true, last_activity: "il y a 2h", last_title: "Baisse taux 25pb", momentum: "Cycle assouplissement", pulse: [1, 2, 1, 2, 3, 2, 3, 4], note: "Source macro principale." },
    { id: "elysee", name: "Élysée / Matignon", mark: "RF", color: "#1e3a8a", followed: true, last_activity: "il y a 4h", last_title: "Conseil des ministres — PLF 2027", momentum: "Pré-électorale", pulse: [3, 4, 2, 5, 3, 4, 4, 3], note: "Politique nationale." },
    { id: "lemonde", name: "Le Monde", mark: "M", color: "#1a1a1a", followed: true, last_activity: "il y a 1h", last_title: "Enquête Caisse des Dépôts", momentum: "Production régulière", pulse: [5, 6, 5, 7, 5, 6, 6, 7], note: "Presse quotidienne référence." },
    { id: "reuters", name: "Reuters / AFP", mark: "R", color: "#ff8000", followed: true, last_activity: "il y a 30 min", last_title: "Accord Mercosur-UE validé", momentum: "Flux continu", pulse: [8, 7, 9, 8, 8, 9, 8, 9], note: "Fil actu internationale." },
    { id: "whitehouse", name: "Maison Blanche", mark: "US", color: "#bf0a30", followed: true, last_activity: "il y a 6h", last_title: "Tarifs douaniers Chine +15%", momentum: "Administration active", pulse: [4, 3, 5, 4, 5, 6, 5, 6], note: "Politique US." },
    { id: "medias-locaux", name: "Presse régionale FR", mark: "FR", color: "#1a5f3f", followed: false, last_activity: "il y a 2h", last_title: "Paris : pic pollution", momentum: "Flux local", pulse: [3, 4, 3, 4, 3, 4, 5, 4], note: "Pas encore suivi — à ajouter ?" },
  ],

  feed: [
    { id: "n1", actor: "BCE", category: "international", type: "Économie", date_h: 2, date_label: "il y a 2h", title: "BCE : baisse des taux de 25 points de base, taux directeur à 2.50%", summary: "2e baisse consécutive. Lagarde confirme la trajectoire désinflationniste. Prochaine réunion en juin, marchés anticipent une pause.", tags: ["#bce", "#taux", "#economie"], unread: true, starred: true, icon: "sparkles" },
    { id: "n2", actor: "Reuters / AFP", category: "international", type: "International", date_h: 0.5, date_label: "il y a 30 min", title: "Accord Mercosur-UE officiellement ratifié par le Parlement européen", summary: "Vote serré : 398 pour, 289 contre, 18 abstentions. La France maintient son opposition. Lula salue une victoire historique. Déploiement progressif sur 15 ans.", tags: ["#ue", "#mercosur", "#commerce"], unread: true, starred: true, icon: "flag" },
    { id: "n3", actor: "Élysée / Matignon", category: "france", type: "Politique", date_h: 4, date_label: "il y a 4h", title: "PLF 2027 : Bayrou annonce 18 Md€ d'économies, débat parlementaire houleux", summary: "Réduction des effectifs de l'État, révision des niches fiscales immobilières, gel du point d'indice. Censure vaguement évoquée par le PS et le RN. Vote prévu fin mai.", tags: ["#budget", "#politique", "#france"], unread: true, starred: true, icon: "alert" },
    { id: "n4", actor: "Maison Blanche", category: "international", type: "International", date_h: 6, date_label: "il y a 6h", title: "Nouvelle salve de tarifs US sur la Chine : +15% sur produits technologiques", summary: "Semiconducteurs, batteries, véhicules électriques concernés. Pékin riposte avec restrictions sur terres rares. Escalade avant la rencontre prévue en juin.", tags: ["#usa", "#chine", "#tarifs"], unread: true, starred: false, icon: "alert" },
    { id: "n5", actor: "Le Monde", category: "france", type: "Enquête", date_h: 1, date_label: "il y a 1h", title: "Enquête : opacité des comptes de la Caisse des Dépôts sur ses participations", summary: "Rapport interne révélé par Le Monde. 40 participations non-consolidées dans les comptes publics pour ~12 Md€. Bercy demande un audit externe.", tags: ["#enquete", "#cdc", "#france"], unread: true, starred: true, icon: "paper" },
    { id: "n6", actor: "Élysée / Matignon", category: "france", type: "Local", date_h: 24, date_label: "hier", title: "Annonce plan logement : 25 Md€ sur 5 ans, focus zones tendues", summary: "Paris, Lyon, Marseille, Toulouse ciblés. Aide 0% étendue aux primo-accédants jusqu'à 45 ans. Réforme DPE allégée pour copropriétés. Les bailleurs sociaux contestent les montants.", tags: ["#logement", "#france", "#politique"], unread: true, starred: false, icon: "check" },
    { id: "n7", actor: "Reuters / AFP", category: "international", type: "International", date_h: 8, date_label: "il y a 8h", title: "Élection Allemagne : Scholz en difficulté, AfD à 22% dans les sondages", summary: "À 3 mois du scrutin fédéral, la CDU de Merz en tête (31%), SPD en 3e position. Coalition inédite envisagée. Impact direct sur l'agenda UE.", tags: ["#allemagne", "#election", "#ue"], unread: false, starred: false, icon: "flag" },
    { id: "n8", actor: "Le Monde", category: "paris", type: "Local", date_h: 12, date_label: "il y a 12h", title: "Paris : pic de pollution aux particules fines, circulation différenciée demain", summary: "Dépassement seuil alerte 3e jour consécutif. Préfecture active Crit'Air ≤3. RATP offre la journée sur métro et RER. Prolongation probable jusqu'au weekend.", tags: ["#paris", "#pollution", "#local"], unread: false, starred: false, icon: "alert" },
    { id: "n9", actor: "Maison Blanche", category: "international", type: "International", date_h: 48, date_label: "il y a 2j", title: "Accord de paix Ukraine : première rencontre Zelensky-Poutine à Genève", summary: "Médiation Vatican + Turquie. Pas d'accord signé mais communiqué conjoint sur cessez-le-feu local. Tenue à Genève sous haute sécurité. Reprise prévue dans 3 semaines.", tags: ["#ukraine", "#russie", "#diplomatie"], unread: false, starred: true, icon: "star" },
    { id: "n10", actor: "BCE", category: "international", type: "Économie", date_h: 120, date_label: "il y a 5j", title: "Lagarde : 'l'euro numérique arrivera en 2028, c'est confirmé'", summary: "Phase pilote élargie à 8 pays dont la France. Pas de remplacement du cash, coexistence. Panel banques commerciales intégré.", tags: ["#bce", "#eurosnum", "#innovation"], unread: false, starred: false, icon: "sparkles" },
    { id: "n11", actor: "Élysée / Matignon", category: "france", type: "Politique", date_h: 72, date_label: "il y a 3j", title: "Remaniement partiel : 3 ministères changent de mains", summary: "Économie, Éducation, Transition écologique. Profils technocratiques privilégiés. Bayrou conserve Matignon. Cote de popularité du PM stable à 28%.", tags: ["#gouvernement", "#remaniement", "#france"], unread: false, starred: false, icon: "flag" },
    { id: "n12", actor: "Reuters / AFP", category: "international", type: "International", date_h: 168, date_label: "il y a 7j", title: "Climat : accord COP31 confirme l'objectif net-zéro 2055 mais reporte financement", summary: "Négociations Belém prolongées de 48h. Pays du Sud obtiennent 400 Md$ sur 10 ans. Financement privé prévu à 60%. Manque d'engagements contraignants pointé par l'ONU.", tags: ["#cop", "#climat", "#international"], unread: false, starred: false, icon: "paper" },
  ],

  prod_cases: [
    { company: "Élection présidentielle 2027", logo_mark: "RF", color: "#1e3a8a", scale: "~48M électeurs", model: "Scrutin national", domain: "Politique FR", when: "Avril-mai 2027", headline: "18 mois avant. Sondages : Attal, Bardella, Mélenchon aux coudes. Primaires LR en octobre.", impact: "Redéfinition politique" },
    { company: "Euro 2028 (impact FR)", logo_mark: "UE", color: "#1e4fa5", scale: "4 villes françaises accueil", model: "Co-organisation UK/IE", domain: "Sport & économie", when: "Juin 2028", headline: "Impact estimé 1.2 Md€ tourisme. Sécurité renforcée, coordination police européenne.", impact: "Enjeu économique régional" },
    { company: "AI Act phase 3", logo_mark: "UE", color: "#003399", scale: "27 pays UE", model: "Régulation", domain: "Tech & droit", when: "1er août 2026", headline: "Systèmes à haut risque : obligations pleines. Impact direct sur 6000+ entreprises françaises.", impact: "Mise en conformité urgente" },
  ],

  trends: [
    {
      id: "tn-desinflation",
      label: "Désinflation européenne",
      kicker: "Cycle macro",
      momentum: "+60% · 60j",
      pulse: [2, 3, 3, 4, 5, 6, 7, 8],
      articles_count: 9,
      summary: "Inflation zone € revenue à 2.1%. BCE en phase d'assouplissement. Pouvoir d'achat légèrement positif. Livret A suivra probablement à la baisse.",
      actors_involved: ["BCE", "INSEE", "Eurostat"],
      status: "rising",
    },
    {
      id: "tn-pre-election",
      label: "Précampagne présidentielle 2027",
      kicker: "Politique française",
      momentum: "+180% · 90j",
      pulse: [1, 2, 3, 4, 6, 8, 11, 14],
      articles_count: 12,
      summary: "Attal, Bardella, Mélenchon positionnés. LR en primaire. PS cherche candidat unique. 18 mois de campagne larvée qui commencent.",
      actors_involved: ["Renaissance", "RN", "LFI", "LR"],
      status: "rising",
    },
    {
      id: "tn-ukraine-diplomacy",
      label: "Négociations Ukraine — timidité",
      kicker: "Diplomatie int.",
      momentum: "+45% · 30j",
      pulse: [2, 2, 3, 3, 4, 4, 5, 5],
      articles_count: 6,
      summary: "Première rencontre Zelensky-Poutine depuis 2019. Médiation Vatican + Turquie. Pas d'accord mais ouverture timide. Europe divisée sur le soutien.",
      actors_involved: ["Ukraine", "Russie", "Vatican", "UE"],
      status: "debated",
    },
    {
      id: "tn-us-trade-war",
      label: "Guerre commerciale US-Chine 2.0",
      kicker: "Géopolitique économique",
      momentum: "+130% · 60j",
      pulse: [2, 3, 4, 5, 6, 8, 10, 12],
      articles_count: 10,
      summary: "Tarifs US sur Chine +40% en 6 mois. Pékin cible terres rares + semi-conducteurs. UE coincée, cherche troisième voie. Impact direct automobiles FR.",
      actors_involved: ["USA", "Chine", "UE", "OMC"],
      status: "rising",
    },
  ],
};
