// ═══════════════════════════════════════════════════════════════
// IDEAS_DATA — Carnet d'idées (l'incubateur)
// ─────────────────────────────────────────────
// Distinction vs OPPORTUNITIES :
//   · Opportunités = fenêtres datées, "je saisis / je passe"
//   · Idées        = backlog SANS deadline, "je laisse mûrir / je creuse / je promeus"
//
// Fields per idée :
//   id, title, category (business|side|content|jarvis|life),
//   kicker, one_liner, body,
//   status : seed | incubating | maturing | ready_to_promote | parked
//   captured_at, last_touched,
//   effort (1-5), impact (1-5), alignment (1-5) → Jarvis score
//   signals[]        — signaux faibles source
//   source           — "idée perso" | "jarvis-suggested" | "from-article"
//   origin           — contexte de la capture (court)
//   touched_count    — nb fois que tu l'as relue/éditée
//   related_ids[]    — liens vers autres idées (clusters)
//   jarvis_prompt    — question socratique que Jarvis pose
//   jarvis_enriched  — objet : si Jarvis a enrichi (similar_companies, market_sig, risks)
//   promoted_to_opp  — id d'une opportunité si promue
// ═══════════════════════════════════════════════════════════════
window.IDEAS_DATA = {
  updated: "Mar 21 avr · 06h14",
  stats: {
    total: 18,
    this_week: 3,          // captured this week
    ready_count: 2,        // ready_to_promote
    avg_age_days: 42,
  },

  // Catégories du carnet
  categories: [
    { id: "business", label: "Business",     sub: "Produits, SaaS, conseil",     color: "#2f2a24" },
    { id: "side",     label: "Side project", sub: "Outils, extensions, repos",   color: "#5a4634" },
    { id: "content",  label: "Contenu",      sub: "Newsletter, talks, threads",  color: "#8a6e4a" },
    { id: "jarvis",   label: "Jarvisception",sub: "Améliorer le cockpit",        color: "#3a4a3a" },
    { id: "life",     label: "Vie perso",    sub: "Rituels, voyages, idées",     color: "#6a4a3a" },
  ],

  // Pipeline de maturité
  stages: [
    { id: "seed",              label: "Graine",            sub: "Captur\u00e9e, pas encore creus\u00e9e" },
    { id: "incubating",        label: "En incubation",     sub: "Je la laisse mon mijoter" },
    { id: "maturing",          label: "En maturation",     sub: "Je la creuse activement" },
    { id: "ready_to_promote",  label: "Pr\u00eate \u00e0 promouvoir", sub: "\u00c0 passer en opportunit\u00e9 ou \u00e0 parquer" },
    { id: "parked",            label: "Park\u00e9e",           sub: "Pas le moment \u2014 \u00e0 relire plus tard" },
  ],

  ideas: [

    // ═══ Graines fraîches (capturées cette semaine) ══════════
    {
      id: "id1",
      category: "business",
      kicker: "Assurance · Vendredi 18 avr, 22h17",
      title: "Et si je proposais un \"AI Act audit sprint\" en 5 jours, format commando ?",
      one_liner: "3-5k\u20ac la mission, livrable standard : cartographie SI + doctrine + plan 6 mois.",
      body: "Not\u00e9e apr\u00e8s le d\u00eener avec Arnaud (DSI Groupama). Il avait bu mais il \u00e9tait convaincant. \"Tu viens 5 jours, tu m'\u00e9cris un truc, je te signe un ch\u00e8que\". Question : est-ce que c'est standardisable ? Qui achete ce format ?",
      status: "seed",
      captured_at: "2026-04-18",
      last_touched: "2026-04-18",
      touched_count: 1,
      effort: 3, impact: 4, alignment: 5,
      signals: ["ai act phase 3"],
      source: "id\u00e9e perso",
      origin: "D\u00eener avec Arnaud (DSI Groupama)",
      related_ids: ["id2", "id3"],
      jarvis_prompt: "Qui paie un audit \u00e0 5k\u20ac plut\u00f4t qu'un cabinet \u00e0 15k\u20ac ? Probablement les ETI < 500 pers. \u2014 tu veux que je mappe ce segment ?",
    },
    {
      id: "id2",
      category: "jarvis",
      kicker: "Cockpit \u00b7 Lun 21 avr, 06h22",
      title: "Ajouter un \"mode lecture\" qui lit les articles \u00e0 voix haute pendant mes trajets",
      one_liner: "Synth\u00e8se audio 5-8 min du brief du jour, g\u00e9n\u00e9r\u00e9e pour le trajet m\u00e9tro.",
      body: "J'ai 38 min de m\u00e9tro aller, 38 retour. Je pourrais \u00e9couter Jarvis me lire les 3 tops + signaux montants. ElevenLabs coute 5c\u20ac/min, soit 30c\u20ac par brief. OK.",
      status: "seed",
      captured_at: "2026-04-21",
      last_touched: "2026-04-21",
      touched_count: 1,
      effort: 2, impact: 3, alignment: 4,
      signals: ["agent memory"],
      source: "id\u00e9e perso",
      origin: "Dans le m\u00e9tro, justement",
      related_ids: [],
      jarvis_prompt: "Format audio \u2192 est-ce que tu retiens aussi bien qu'en lisant ? \u00c0 tester une semaine.",
    },
    {
      id: "id3",
      category: "content",
      kicker: "Observation \u00b7 Dim 20 avr, 09h42",
      title: "Newsletter \"Signaux faibles IA assurance\" \u2014 hebdomadaire, FR, ultra-nich\u00e9e",
      one_liner: "Ce que personne ne lit encore mais qui comptera dans 6 mois. Free 6 mois, puis 15\u20ac/mois.",
      body: "Tu as d\u00e9j\u00e0 la mati\u00e8re (6 signaux/sem), tu as d\u00e9j\u00e0 l'audience LinkedIn (2400 abonn\u00e9s). Substack \u2192 3-5k abonn\u00e9s gratuits en 6 mois = 200-300 payants \u00e0 15\u20ac = 3-4k\u20ac/mois. Side stream solide.",
      status: "seed",
      captured_at: "2026-04-20",
      last_touched: "2026-04-20",
      touched_count: 1,
      effort: 3, impact: 4, alignment: 5,
      signals: ["ai act phase 3", "agent memory", "small language models"],
      source: "id\u00e9e perso",
      origin: "Caf\u00e9 dimanche matin",
      related_ids: ["id8", "id14"],
      jarvis_prompt: "3 concurrents en anglais, 0 en fran\u00e7ais. Positionnement clair. Veux-tu que je mappe les 20 premiers sujets ?",
    },

    // ═══ En incubation (depuis quelques semaines) ════════════
    {
      id: "id4",
      category: "business",
      kicker: "Assurance \u00b7 Il y a 2 semaines",
      title: "Agent de relecture de contrats d'assurance avec context Malakoff",
      one_liner: "LLM qui conna\u00eet la doctrine + r\u00e8gles m\u00e9tier + jurisprudence, annote les contrats.",
      body: "Constat\u00e9 en comit\u00e9 : les chefs de produit passent 30% du temps \u00e0 relire des contrats en se demandant \"on a d\u00e9j\u00e0 une doctrine sur ce point ?\". Corpus existe (300 pages markdown). Pipeline RAG + LLM judge. 6 semaines de construction, 0 adhoc marketing n\u00e9cessaire (besoin interne).",
      status: "incubating",
      captured_at: "2026-04-07",
      last_touched: "2026-04-15",
      touched_count: 4,
      effort: 3, impact: 5, alignment: 5,
      signals: ["agent memory", "context engineering", "ai act phase 3"],
      source: "from-article",
      origin: "Apr\u00e8s le papier DeepMind sur les agents juridiques",
      related_ids: ["id1", "id11"],
      jarvis_prompt: "L'objection classique : \"et si l'agent hallucine sur un point r\u00e9gu ?\". Quel garde-fou tu mets ?",
      jarvis_enriched: {
        similar_companies: ["Harvey", "Casetext CoCounsel", "Luminance"],
        market_sig: "Levées récentes 2025-2026 : Harvey 400M, Luminance 75M. Marché chaud, mais focus cabinets d'avocats — assurance sous-servi.",
        risks: "RGPD (contrats = données clients). Besoin cloud souverain → Mistral plutôt que Claude.",
      },
    },
    {
      id: "id5",
      category: "side",
      kicker: "Dev perso \u00b7 Il y a 3 semaines",
      title: "Extension Chrome \"R\u00e9sume cet article en contexte veille\"",
      one_liner: "1 clic : Claude r\u00e9sume l'article + rattache aux signaux faibles + stocke dans le carnet.",
      body: "Tu lis 47 articles/jour. 20 min de lecture \u00e9conomis\u00e9es \u2192 2h/sem. Stack : manifest v3, popup minimal, appel Claude avec system prompt de contexte (tes signaux + wiki). Stockage local, sync avec cockpit. Weekend de code.",
      status: "incubating",
      captured_at: "2026-04-01",
      last_touched: "2026-04-10",
      touched_count: 3,
      effort: 1, impact: 4, alignment: 5,
      signals: ["agent memory", "mcp"],
      source: "id\u00e9e perso",
      origin: "Frustration en lisant Techcrunch \u00e0 10h le lundi",
      related_ids: ["id2", "id10"],
      jarvis_prompt: "Si tu la publies sur le Chrome Store : nom ? prix (gratuit/free-tier/payant) ? c'est un side-funnel vers le cockpit ou un produit standalone ?",
      jarvis_enriched: {
        similar_companies: ["Readwise Reader", "MyMind", "Glasp"],
        market_sig: "Segment overcrowded en B2C. Mais aucun outil n'est centr\u00e9 sur la veille pro avec contexte signaux.",
        risks: "Tu vas vouloir en faire un produit. Pense si c'est vraiment ce que tu veux, ou juste un outil perso.",
      },
    },
    {
      id: "id6",
      category: "jarvis",
      kicker: "Cockpit \u00b7 Il y a 10 jours",
      title: "Post-mortem hebdo automatique : Jarvis me demande 3 questions le vendredi soir",
      one_liner: "\"Qu'est-ce qui t'a fait t'arr\u00eater cette semaine ? Qu'est-ce que tu referais ? Une d\u00e9cision \u00e0 prendre ?\"",
      body: "Format : 5 min, r\u00e9ponses vocales \u2192 transcrites \u2192 alim. le Wiki. Sur 6 mois = 200 pages de reflexions tri\u00e9es. Jarvis peut ensuite croiser pour rep\u00e9rer des patterns.",
      status: "incubating",
      captured_at: "2026-04-11",
      last_touched: "2026-04-16",
      touched_count: 2,
      effort: 1, impact: 3, alignment: 4,
      signals: ["agent memory", "context engineering"],
      source: "id\u00e9e perso",
      origin: "Apr\u00e8s avoir lu le livre \"Show Your Work\"",
      related_ids: ["id2"],
      jarvis_prompt: "Le vendredi soir, tu as envie de d\u00e9crocher. Tu veux vraiment que je t'interrompe ? \u2014 propose plut\u00f4t lundi matin.",
    },
    {
      id: "id7",
      category: "content",
      kicker: "R\u00e9seau \u00b7 Il y a 2 semaines",
      title: "Talk \"Comment on a construit un cockpit IA perso\" \u2014 DevFest Nantes",
      one_liner: "45 min, technique + philo, avec demo live. Deadline soumission : 15 mai.",
      body: "Angle : la veille IA est devenu impossible \u00e0 faire humainement. Je montre comment j'ai d\u00e9l\u00e9gu\u00e9 le tri \u00e0 Claude, gard\u00e9 le sens pour moi. D\u00e9mo live : lit un article \u2192 montre comment il atterrit en opportunit\u00e9 dat\u00e9e.",
      status: "incubating",
      captured_at: "2026-04-08",
      last_touched: "2026-04-18",
      touched_count: 5,
      effort: 2, impact: 4, alignment: 4,
      signals: ["agent memory", "context engineering"],
      source: "id\u00e9e perso",
      origin: "CFP DevFest sort\u00e9 le 7 avril",
      related_ids: ["id3", "id13"],
      jarvis_prompt: "Si t'es accept\u00e9 : tu as 5 mois pour pr\u00e9parer. Tu pr\u00e9f\u00e8res r\u00e9p\u00e9ter en meetup d'abord ?",
    },

    // ═══ En maturation (activement creusées) ═════════════════
    {
      id: "id8",
      category: "business",
      kicker: "Assurance \u00b7 Il y a 5 semaines",
      title: "Micro-SaaS d'audit AI Act automatis\u00e9 pour PME",
      one_liner: "Scan Notion/Drive + rapport conformit\u00e9 \u2192 300-800\u20ac/mois par PME.",
      body: "V0 en 3 mois de weekend. Auth, connecteurs Google Drive + Notion + GitHub, LLM judge avec prompt AI Act phase 3, export PDF. TAM ciblé : 40k PME FR avec > 20 salariés et qui utilisent de l'IA.",
      status: "maturing",
      captured_at: "2026-03-17",
      last_touched: "2026-04-19",
      touched_count: 12,
      effort: 4, impact: 5, alignment: 4,
      signals: ["ai act phase 3", "small language models"],
      source: "id\u00e9e perso",
      origin: "Enqu\u00eate BPI France sur les PME et l'IA",
      related_ids: ["id4", "id3"],
      jarvis_prompt: "Tu as not\u00e9 \"je d\u00e9teste vendre PME\". C'est le vrai blocage. Qui fait la partie commerciale ? Un associ\u00e9 ? Ou channel (cabinets comptables) ?",
      jarvis_enriched: {
        similar_companies: ["Credo AI", "Holistic AI", "Vera"],
        market_sig: "Segment naissant en Europe. Aucun pure-player FR. Concurrents US chers (2k\u20ac+/mois).",
        risks: "L'obligation r\u00e9elle arrive en ao\u00fbt 2026. Tu dois \u00eatre en vente sous 3 mois.",
      },
      promoted_to_opp: "op3",   // lié à l'opportunité existante
    },
    {
      id: "id9",
      category: "jarvis",
      kicker: "Cockpit \u00b7 Il y a 6 semaines",
      title: "Brancher Jarvis sur la bo\u00eete mail Outlook pour auto-tagger les opportunit\u00e9s",
      one_liner: "MCP server \u2192 mail \u2192 extraction entities \u2192 classification opportunit\u00e9 / signal / bruit.",
      body: "70% des vraies opportunit\u00e9s viennent par mail. Auj aucune n'est trac\u00e9e. Jarvis lit les mails, classifie, ajoute au carnet comme graines. Accept/reject humain ensuite. Stack : MCP Microsoft + Claude Haiku pour le tri.",
      status: "maturing",
      captured_at: "2026-03-10",
      last_touched: "2026-04-20",
      touched_count: 8,
      effort: 2, impact: 5, alignment: 5,
      signals: ["mcp", "agent memory"],
      source: "id\u00e9e perso",
      origin: "Retrospective perso de mars",
      related_ids: ["id2", "id6"],
      jarvis_prompt: "S\u00e9curit\u00e9 : tu passes tous tes mails \u00e0 Anthropic ? C'est dans le scope de Malakoff ? \u2014 faut clarifier avec RSSI.",
      jarvis_enriched: {
        similar_companies: ["Superhuman AI", "Shortwave", "Fyxer"],
        market_sig: "B2C overcrowded mais pas de pure-player B2B-perso-d\u00e9veloppeur avec MCP.",
        risks: "RGPD. Test d'abord sur ta boîte perso.",
      },
      promoted_to_opp: "op10",
    },

    // ═══ Prêtes à promouvoir ═════════════════════════════════
    {
      id: "id10",
      category: "side",
      kicker: "Dev perso \u00b7 Mature depuis 8 semaines",
      title: "Publier ton \"awesome-ai-act\" sur GitHub",
      one_liner: "Liste curat\u00e9e des outils, ressources, cas d'usage AI Act. 2h de mise en forme, potentiel viral.",
      body: "Tu as d\u00e9j\u00e0 le corpus (~80 liens tag\u00e9s). awesome-* sur GitHub = recette \u00e9prouv\u00e9e. Low effort, signal fort sur ton positionnement. Risque \u00ab z\u00e9ro \u00bb.",
      status: "ready_to_promote",
      captured_at: "2026-02-25",
      last_touched: "2026-04-18",
      touched_count: 9,
      effort: 1, impact: 3, alignment: 5,
      signals: ["ai act phase 3"],
      source: "id\u00e9e perso",
      origin: "Vu awesome-llm de Hannibal046",
      related_ids: ["id3", "id7"],
      jarvis_prompt: "Cette id\u00e9e est prête depuis 8 semaines. La vraie question : est-ce que tu procrastines ? — 2h ce samedi.",
      promoted_to_opp: "op4",
    },
    {
      id: "id11",
      category: "business",
      kicker: "Assurance \u00b7 Mature depuis 9 semaines",
      title: "Offre \"AI Act pour d\u00e9cideurs assurance\" en 3h, format flash",
      one_liner: "4-6k\u20ac la session COMEX. 8 mutuelles dans le r\u00e9seau imm\u00e9diat.",
      body: "Tu as d\u00e9j\u00e0 anim\u00e9 4 ateliers internes. Le contenu existe \u00e0 70%, reste \u00e0 le formater en offre payante. C'est l'opportunit\u00e9 la plus mûre du carnet — elle attend juste une d\u00e9cision.",
      status: "ready_to_promote",
      captured_at: "2026-02-18",
      last_touched: "2026-04-20",
      touched_count: 14,
      effort: 2, impact: 4, alignment: 5,
      signals: ["ai act phase 3", "context engineering"],
      source: "id\u00e9e perso",
      origin: "Retour d'un atelier CODIR Malakoff",
      related_ids: ["id1", "id4"],
      jarvis_prompt: "Tu as tout. Pricing clair, contenu pr\u00eat, r\u00e9seau chaud. La seule chose qui manque : la d\u00e9cision de lancer. \u00c0 quoi tu attends ?",
      promoted_to_opp: "op2",
    },

    // ═══ Parquées (pas le bon moment) ════════════════════════
    {
      id: "id12",
      category: "business",
      kicker: "Parqu\u00e9e il y a 4 mois",
      title: "Plateforme de matching freelance IA \u00d7 mutuelles",
      one_liner: "Marketplace ni\u00e9e. March\u00e9 encore trop immature.",
      body: "Id\u00e9e eu en janvier. Apr\u00e8s 3 appels, verdict : les mutuelles n'ach\u00e8tent pas des freelances, elles ach\u00e8tent des cabinets. Pas le bon moment, peut-\u00eatre dans 2 ans.",
      status: "parked",
      captured_at: "2026-01-03",
      last_touched: "2026-01-25",
      touched_count: 6,
      effort: 5, impact: 4, alignment: 3,
      signals: [],
      source: "id\u00e9e perso",
      origin: "Discussion avec Julie sur sa plateforme design",
      related_ids: [],
      jarvis_prompt: "\u00c0 relire dans 6 mois quand le march\u00e9 mutuelles aura internalis\u00e9 l'AI Act.",
    },
    {
      id: "id13",
      category: "content",
      kicker: "Parqu\u00e9e il y a 2 mois",
      title: "Podcast \"D\u00e9crypter l'IA avec un praticien\"",
      one_liner: "1h, invit\u00e9 tech lead, angle concret. Mais 10h de prod par \u00e9pisode.",
      body: "Tent\u00e9 un pilote en f\u00e9vrier. Verdict : l'effort \u00e9ditorial est \u00e9norme, le gain audience incertain en 2026 (march\u00e9 satur\u00e9). \u00c0 reprendre seulement si j'ai un angle unique et 3 mois de contenu pr\u00eat.",
      status: "parked",
      captured_at: "2026-02-01",
      last_touched: "2026-02-28",
      touched_count: 4,
      effort: 5, impact: 3, alignment: 3,
      signals: [],
      source: "id\u00e9e perso",
      origin: "Lu 3 articles sur l'\u00e9cosyst\u00e8me podcast FR",
      related_ids: ["id7"],
      jarvis_prompt: "La vraie contrainte : tu n'aimes pas le montage. Sans partenaire \u00e9diteur, \u00e7a ne tient pas.",
    },

    // ═══ Autres idées ═════════════════════════════════════════
    {
      id: "id14",
      category: "content",
      kicker: "Incubation \u00b7 4 semaines",
      title: "Thread LinkedIn : \"10 signaux faibles IA que personne ne regarde\"",
      one_liner: "Format carrousel, sortir avant un concurrent. 2h de prod.",
      body: "Tu as la mati\u00e8re. Format carrousel LinkedIn = engagement x3 vs texte. Angle contrarian : non, GPT-5 n'est pas le plus important.",
      status: "incubating",
      captured_at: "2026-03-24",
      last_touched: "2026-04-12",
      touched_count: 3,
      effort: 1, impact: 3, alignment: 4,
      signals: ["agent memory", "small language models", "context engineering"],
      source: "id\u00e9e perso",
      origin: "Vu un carrousel de Philippe Stoll",
      related_ids: ["id3"],
      jarvis_prompt: "Si tu le fais, tu as 3 semaines avant que 5 concurrents fassent pareil. Cette semaine ou jamais.",
    },
    {
      id: "id15",
      category: "side",
      kicker: "Graine \u00b7 Il y a 3 jours",
      title: "Bot Telegram \"Rappelle-moi les signaux faibles tous les dimanches\"",
      one_liner: "10 min de dev avec webhook. Utile pour moi, potentiel cadeau \u00e0 la communaut\u00e9.",
      body: "Le dimanche soir, je veux jeter un œil aux signaux montants sans ouvrir le cockpit. Bot Telegram \u2192 sum\u00e9 + top 3 signaux \u2192 click = cockpit.",
      status: "seed",
      captured_at: "2026-04-18",
      last_touched: "2026-04-18",
      touched_count: 1,
      effort: 1, impact: 2, alignment: 3,
      signals: ["mcp"],
      source: "id\u00e9e perso",
      origin: "Dimanche soir, couch\u00e9, pas envie d'ouvrir le laptop",
      related_ids: ["id2"],
      jarvis_prompt: "Weekend de dev. Ou \u2014 plus simple \u2014 c'est d\u00e9j\u00e0 un mail le dimanche ?",
    },
    {
      id: "id16",
      category: "life",
      kicker: "Graine \u00b7 Il y a 1 semaine",
      title: "Annuler Netflix et prendre un abonnement livres audio (Audible)",
      one_liner: "Tu regardes Netflix \u00e0 peine 2h/sem. Audible serait plus utile dans le m\u00e9tro.",
      body: "Budget \u00e9quivalent. Plus align\u00e9 avec \"mode lecture\" que j'ai not\u00e9 (id2). Test sur 2 mois.",
      status: "seed",
      captured_at: "2026-04-14",
      last_touched: "2026-04-14",
      touched_count: 1,
      effort: 1, impact: 2, alignment: 3,
      signals: [],
      source: "id\u00e9e perso",
      origin: "Apr\u00e8s avoir pay\u00e9 Netflix sans rien regarder ce mois",
      related_ids: ["id2"],
      jarvis_prompt: null,
    },
    {
      id: "id17",
      category: "jarvis",
      kicker: "Sugg\u00e9r\u00e9 par Jarvis \u00b7 Il y a 2 jours",
      title: "Ajouter un \"mode challenge Fine-tune\" au cockpit",
      one_liner: "Jarvis propose chaque semaine un LoRA \u00e0 tenter en 2h. Tu as 38/100 sur fine-tuning.",
      body: "Corr\u00e9l\u00e9 \u00e0 ton radar : fine-tuning = ton plus gros gap. Le cockpit devrait te pousser 1 mini-challenge/semaine. Int\u00e9gration avec le panel Challenges existant.",
      status: "incubating",
      captured_at: "2026-04-19",
      last_touched: "2026-04-19",
      touched_count: 1,
      effort: 2, impact: 3, alignment: 3,
      signals: ["small language models"],
      source: "jarvis-suggested",
      origin: "Jarvis a d\u00e9tect\u00e9 le gap radar + articles r\u00e9cents LoRA",
      related_ids: ["id6"],
      jarvis_prompt: "C'est moi qui l'ai sugg\u00e9r\u00e9e. Je te recommande de la parquer jusqu'\u00e0 ce que tu aies fini le challenge Qwen3 en cours.",
    },
    {
      id: "id18",
      category: "life",
      kicker: "Incubation \u00b7 Il y a 5 semaines",
      title: "Rituel du samedi matin : 2h de lecture deep, t\u00e9l\u00e9phone en mode avion",
      one_liner: "Tu l'as fait 3 samedis sur 6. \u00c0 syst\u00e9matiser ?",
      body: "Quand tu l'as fait : meilleure semaine de productivit\u00e9 derri\u00e8re. Corr\u00e9lation claire dans le wiki. Ritualiser = ins\u00e9rer dans le calendrier + dire non aux sorties tardives vendredi.",
      status: "incubating",
      captured_at: "2026-03-17",
      last_touched: "2026-04-13",
      touched_count: 3,
      effort: 1, impact: 4, alignment: 4,
      signals: [],
      source: "id\u00e9e perso",
      origin: "Constatation hebdo du cockpit",
      related_ids: [],
      jarvis_prompt: "Tu as les data : 3/6 samedis = meilleure semaine. Statistiquement, c'est significatif. Verrouille la place dans l'agenda.",
    },
  ],
};
