// Veille IA — corpus enrichi : releases, acteurs, cas prod
window.VEILLE_DATA = {
  // Dernière release majeure pour le hero
  headline: {
    kicker: "Release · il y a 2h",
    actor: "Anthropic",
    version: "Claude 4.5 Sonnet",
    tagline: "Le premier modèle à passer SWE-bench Verified au-dessus de 70%",
    body: "Sortie surprise hier soir. Anthropic remonte devant GPT-5 sur les benchmarks code et agents. Mémoire persistante de 1M tokens disponible en GA, pricing inchangé. Trois assureurs français déjà en POC ce matin.",
    metrics: [
      { label: "SWE-bench Verified", value: "71.3%", delta: "+8.2" },
      { label: "τ-bench (agents)", value: "84.1%", delta: "+11.5" },
      { label: "Prix input", value: "$3/M", delta: "=" },
      { label: "Contexte", value: "1M tok", delta: "×5" },
    ],
    tags: ["#release", "#anthropic", "#code", "#agents"],
  },

  // Acteurs suivis (cartes)
  actors: [
    {
      id: "anthropic",
      name: "Anthropic",
      mark: "A",
      color: "#c06443",
      followed: true,
      last_activity: "il y a 2h",
      last_title: "Claude 4.5 Sonnet · GA",
      momentum: "+3 releases · 30j",
      pulse: [2, 3, 1, 4, 2, 5, 3, 6],
      note: "Ton acteur le plus suivi. 14 articles lus ce mois.",
    },
    {
      id: "openai",
      name: "OpenAI",
      mark: "○",
      color: "#0d7a5f",
      followed: true,
      last_activity: "il y a 9h",
      last_title: "Swarm v2 SDK · handoffs explicites",
      momentum: "+5 releases · 30j",
      pulse: [4, 3, 5, 2, 4, 6, 4, 5],
      note: "Cadence soutenue. Focus agents + voix.",
    },
    {
      id: "mistral",
      name: "Mistral",
      mark: "M",
      color: "#b8502c",
      followed: true,
      last_activity: "il y a 4h",
      last_title: "Partenariat BNP Paribas · 140 cas d'usage",
      momentum: "+2 releases · 30j",
      pulse: [1, 2, 1, 3, 2, 2, 4, 3],
      note: "Stratégie enterprise / souveraineté.",
    },
    {
      id: "meta",
      name: "Meta",
      mark: "M",
      color: "#3a5f8a",
      followed: true,
      last_activity: "il y a 1j",
      last_title: "Llama 4 Scout · 10M contexte",
      momentum: "+1 release · 30j",
      pulse: [1, 0, 2, 1, 0, 1, 2, 1],
      note: "Release majeure la semaine dernière.",
    },
    {
      id: "google",
      name: "Google DeepMind",
      mark: "G",
      color: "#4a6fa5",
      followed: false,
      last_activity: "il y a 2j",
      last_title: "Gemini 3 Pro · raisonnement renforcé",
      momentum: "+4 releases · 30j",
      pulse: [3, 2, 4, 3, 2, 3, 2, 3],
      note: "Pas encore suivi — à ajouter ?",
    },
    {
      id: "microsoft",
      name: "Microsoft",
      mark: "▣",
      color: "#2b6f8a",
      followed: true,
      last_activity: "il y a 7h",
      last_title: "Phi-4 mini · 3.8B niveau GPT-4o-mini",
      momentum: "+3 releases · 30j",
      pulse: [2, 3, 2, 2, 3, 2, 3, 2],
      note: "Focus SLM (small language models).",
    },
  ],

  // Feed chronologique
  feed: [
    {
      id: "f1",
      actor: "Anthropic",
      type: "Release",
      date_h: 2,
      date_label: "il y a 2h",
      title: "Claude 4.5 Sonnet — 71.3% SWE-bench, 1M tokens GA",
      summary: "Surprise release hier soir. Nouveau SOTA sur code et agents. Pricing inchangé vs 4.0. Mémoire persistante disponible pour tous les plans entreprise.",
      tags: ["#release", "#llm", "#code"],
      unread: true,
      starred: true,
      icon: "sparkles",
    },
    {
      id: "f2",
      actor: "OpenAI",
      type: "Framework",
      date_h: 9,
      date_label: "il y a 9h",
      title: "Swarm v2 SDK — orchestration multi-agents avec handoffs explicites",
      summary: "Réponse directe à Claude Agents SDK. Python + Node. Handoffs nommés, instrumentation OpenTelemetry native, support MCP.",
      tags: ["#release", "#agent", "#sdk"],
      unread: true,
      starred: false,
      icon: "bot",
    },
    {
      id: "f3",
      actor: "Mistral",
      type: "Deal",
      date_h: 4,
      date_label: "il y a 4h",
      title: "BNP Paribas industrialise 140 cas d'usage IA avec Mistral",
      summary: "Mistral Large 2 en production sur cloud souverain. 40 cas en assurance : souscription, relation conseiller, documentaire. Contrat 5 ans.",
      tags: ["#enterprise", "#finserv", "#souveraineté"],
      unread: true,
      starred: true,
      icon: "bank",
    },
    {
      id: "f4",
      actor: "Microsoft",
      type: "Release",
      date_h: 7,
      date_label: "il y a 7h",
      title: "Phi-4 mini publié — 3.8B paramètres, niveau GPT-4o-mini",
      summary: "Microsoft publie Phi-4 mini sous MIT. Benchmarks compétitifs sur raisonnement et math. Cible edge / mobile.",
      tags: ["#release", "#slm", "#open-source"],
      unread: false,
      starred: false,
      icon: "cpu",
    },
    {
      id: "f5",
      actor: "Axa",
      type: "Cas prod",
      date_h: 14,
      date_label: "il y a 14h",
      title: "Axa France déploie un agent claims sur 2M sinistres auto / an",
      summary: "Retour d'expérience détaillé. Architecture : Claude + Azure + Milvus. Baisse de 23% du temps de traitement, satisfaction client +14 pts NPS.",
      tags: ["#cas-prod", "#assurance", "#agent"],
      unread: true,
      starred: false,
      icon: "shield",
    },
    {
      id: "f6",
      actor: "Google DeepMind",
      type: "Release",
      date_h: 18,
      date_label: "il y a 18h",
      title: "Gemini 3 Pro — raisonnement multi-étapes renforcé",
      summary: "Nouveau SOTA MMLU-Pro à 84.2%. Fenêtre contexte 2M tokens. Accès API public limité aux clients Workspace Enterprise.",
      tags: ["#release", "#llm", "#benchmark"],
      unread: false,
      starred: false,
      icon: "sparkles",
    },
    {
      id: "f7",
      actor: "Anthropic",
      type: "Framework",
      date_h: 26,
      date_label: "il y a 1j",
      title: "MCP 1.2 — serveurs distants authentifiés par OAuth 2.1",
      summary: "Le Model Context Protocol gagne le support natif OAuth et la négociation de version. 4 SDKs majeurs alignés (Python, TS, Go, Rust).",
      tags: ["#protocol", "#mcp", "#agent"],
      unread: false,
      starred: true,
      icon: "plug",
    },
    {
      id: "f8",
      actor: "Meta",
      type: "Release",
      date_h: 30,
      date_label: "il y a 1j",
      title: "Llama 4 Scout — 10M tokens de contexte, open weights",
      summary: "Modèle 109B paramètres activés sur 17B (MoE). Contexte étendu à 10M via RoPE ajusté. License communautaire.",
      tags: ["#release", "#llm", "#open-source"],
      unread: false,
      starred: false,
      icon: "cpu",
    },
    {
      id: "f9",
      actor: "Societe Generale",
      type: "Cas prod",
      date_h: 38,
      date_label: "il y a 2j",
      title: "Agora, l'assistant interne de la SG, passe à 85k utilisateurs actifs",
      summary: "Déploiement sur toute la banque de détail. RAG sur documents internes + Claude Sonnet. 40% des conseillers l'utilisent quotidiennement.",
      tags: ["#cas-prod", "#finserv", "#rag"],
      unread: false,
      starred: false,
      icon: "bank",
    },
    {
      id: "f10",
      actor: "CNIL",
      type: "Régulation",
      date_h: 14,
      date_label: "il y a 14h",
      title: "Référentiel IA publié — focus explicite sur l'assurance santé",
      summary: "Guidelines précises pour conformité RGPD + AI Act. L'assurance santé devient un focus explicite avec 12 contrôles-clés.",
      tags: ["#régulation", "#assurance", "#rgpd"],
      unread: true,
      starred: false,
      icon: "scale",
    },
    {
      id: "f11",
      actor: "Arxiv",
      type: "Papier",
      date_h: 12,
      date_label: "il y a 12h",
      title: "Context engineering : taxonomie des patterns pour agents",
      summary: "Papier qui remplace 'prompt engineering' par 'context engineering'. Taxonomie de 14 patterns observés dans les systèmes multi-agents en production.",
      tags: ["#papier", "#agent", "#contexte"],
      unread: true,
      starred: true,
      icon: "paper",
    },
    {
      id: "f12",
      actor: "a16z",
      type: "Analyse",
      date_h: 18,
      date_label: "il y a 18h",
      title: "The AI insurance stack — 2026 state of the market",
      summary: "Mapping des 140 startups IA en assurance. Trois couches : ingestion, raisonnement, interface. Consolidation à venir sur la couche intermédiaire.",
      tags: ["#analyse", "#assurance", "#market"],
      unread: true,
      starred: false,
      icon: "chart",
    },
  ],

  // Cas prod (déjà filtrable depuis feed, version détaillée)
  prod_cases: [
    {
      company: "BNP Paribas",
      logo_mark: "BNP",
      color: "#00915a",
      scale: "140 cas d'usage",
      model: "Mistral Large 2",
      domain: "Banque + Assurance",
      when: "Avril 2026",
      headline: "Industrialisation à l'échelle sur cloud souverain, dont 40 cas en assurance.",
      impact: "Contrat 5 ans · souveraineté",
    },
    {
      company: "Axa France",
      logo_mark: "AXA",
      color: "#00008f",
      scale: "2M sinistres/an",
      model: "Claude 4 + Milvus",
      domain: "Assurance Auto",
      when: "Mars 2026",
      headline: "Agent claims autonome sur sinistres auto. Baisse 23% temps de traitement.",
      impact: "NPS +14 pts",
    },
    {
      company: "Société Générale",
      logo_mark: "SG",
      color: "#e60028",
      scale: "85k users actifs",
      model: "Claude Sonnet + RAG",
      domain: "Banque détail",
      when: "Février 2026",
      headline: "Agora, assistant conseiller, déployé sur toute la banque de détail.",
      impact: "40% usage quotidien",
    },
    {
      company: "Allianz",
      logo_mark: "A",
      color: "#0033a0",
      scale: "18 pays",
      model: "GPT-5 + AWS Bedrock",
      domain: "Assurance multi-lignes",
      when: "Janvier 2026",
      headline: "Plateforme agents unifiée pour souscription, claims et fraude.",
      impact: "ROI 14 mois",
    },
  ],
  // Tendances transverses — sujets indépendants des gros acteurs
  trends: [
    {
      id: "t-ctx-eng",
      label: "Context engineering",
      kicker: "Pratique émergente",
      momentum: "+312% · 30j",
      pulse: [0, 1, 2, 3, 5, 8, 14, 23],
      articles_count: 9,
      summary: "Remplace progressivement 'prompt engineering'. L'enjeu n'est plus le prompt mais l'orchestration du contexte : mémoire, tool-calling, RAG, cache.",
      actors_involved: ["Anthropic", "OpenAI", "Arxiv", "Chip Huyen"],
      status: "rising",
    },
    {
      id: "t-slm",
      label: "Small Language Models",
      kicker: "Segment marché",
      momentum: "+180% · 30j",
      pulse: [2, 3, 4, 5, 8, 12, 16, 18],
      articles_count: 7,
      summary: "Modèles < 10B qui performent proche des grands sur tâches ciblées. Phi-4, Gemma 3, Qwen 3 Small. Déploiement edge + coûts /10.",
      actors_involved: ["Microsoft", "Google", "Alibaba", "Meta"],
      status: "rising",
    },
    {
      id: "t-ai-act-3",
      label: "AI Act phase 3",
      kicker: "Régulation",
      momentum: "Nouveau",
      pulse: [0, 0, 0, 0, 0, 0, 0, 12],
      articles_count: 5,
      summary: "Guide d'application publié le 17/04. Les systèmes d'aide à la souscription, scoring, pricing entrent explicitement dans 'haut risque'. Entrée en vigueur 1er août.",
      actors_involved: ["Commission EU", "CNIL", "ACPR"],
      status: "new",
    },
    {
      id: "t-mcp-protocol",
      label: "MCP comme standard",
      kicker: "Protocole",
      momentum: "Stabilisé",
      pulse: [38, 42, 40, 39, 41, 43, 39, 41],
      articles_count: 6,
      summary: "Model Context Protocol adopté par 4 éditeurs majeurs. OAuth 2.1, négociation de version, ~200 serveurs publics. Devient de facto le standard.",
      actors_involved: ["Anthropic", "OpenAI", "Google", "Cursor"],
      status: "stable",
    },
    {
      id: "t-agents-prod",
      label: "Agents en production",
      kicker: "Maturation marché",
      momentum: "+95% · 60j",
      pulse: [3, 4, 5, 6, 8, 10, 12, 14],
      articles_count: 11,
      summary: "Les PoC 2024 deviennent des déploiements réels en 2026. BNP, Axa, SG — premiers ROI chiffrés. Architecture moyenne : Claude + RAG vectoriel + orchestration maison.",
      actors_involved: ["BNP", "Axa", "SG", "Allianz"],
      status: "rising",
    },
    {
      id: "t-eval",
      label: "Éval & benchmarks",
      kicker: "Débat scientifique",
      momentum: "Débattu",
      pulse: [5, 6, 4, 7, 5, 8, 6, 9],
      articles_count: 8,
      summary: "Benchmarks saturés (MMLU, HumanEval). Arrivée de τ-bench et SWE-bench Verified. Consensus : l'éval en conditions réelles devient critique pour les agents.",
      actors_involved: ["Arxiv", "HuggingFace", "LMSys"],
      status: "debated",
    },
  ],
};
