// Anime / Cinéma / Séries — corpus
window.ANIME_DATA = {
  headline: {
    kicker: "Sortie · il y a 6h",
    actor: "MAPPA",
    version: "Chainsaw Man Saison 2",
    tagline: "MAPPA relance Chainsaw Man avec un budget record et un nouveau réalisateur",
    body: "Diffusion surprise du premier épisode ce matin. Animation 2D traditionnelle retrouvée après l'accueil mitigé de la saison 1 trop CGI. Arc Academy lancé direct. Score 9.4 sur MyAnimeList après 12h.",
    metrics: [
      { label: "MAL Score", value: "9.4", delta: "+0.8" },
      { label: "Épisodes", value: "24", delta: "+12" },
      { label: "Budget ep.", value: "~2M$", delta: "+30%" },
      { label: "Studio", value: "MAPPA", delta: "=" },
    ],
    tags: ["#anime", "#mappa", "#chainsawman", "#s2"],
  },

  actors: [
    { id: "mappa", name: "MAPPA", mark: "M", color: "#1f1f1f", followed: true, last_activity: "il y a 6h", last_title: "Chainsaw Man S2 ep1", momentum: "3 productions phares 2026", pulse: [2, 3, 2, 4, 3, 4, 5, 5], note: "Studio anime le plus suivi." },
    { id: "a24", name: "A24", mark: "A", color: "#111", followed: true, last_activity: "il y a 1j", last_title: "Nouveau Ari Aster annoncé", momentum: "5 sorties 2026", pulse: [2, 1, 2, 2, 3, 2, 3, 2], note: "Référence cinéma indé." },
    { id: "ghibli", name: "Studio Ghibli", mark: "G", color: "#2e6a4f", followed: true, last_activity: "il y a 4j", last_title: "Miyazaki confirme son retour", momentum: "Retour événement", pulse: [0, 0, 1, 0, 0, 1, 0, 2], note: "Productions rares mais majeures." },
    { id: "hbo", name: "HBO", mark: "H", color: "#9146ff", followed: true, last_activity: "il y a 3h", last_title: "The Last of Us S3 en production", momentum: "Line-up 2026 dense", pulse: [3, 2, 4, 3, 4, 3, 5, 4], note: "Séries prestige." },
    { id: "netflix", name: "Netflix", mark: "N", color: "#e50914", followed: false, last_activity: "il y a 8h", last_title: "Squid Game 3 finale", momentum: "Fin grosse licence", pulse: [4, 5, 4, 5, 4, 4, 5, 4], note: "Pas encore suivi — à ajouter ?" },
    { id: "kyoani", name: "Kyoto Animation", mark: "K", color: "#c8a15a", followed: true, last_activity: "il y a 5j", last_title: "Violet Evergarden : film final", momentum: "Retour après reconstruction", pulse: [0, 0, 1, 0, 1, 0, 1, 1], note: "Suivi par respect + qualité." },
  ],

  feed: [
    { id: "a1", actor: "MAPPA", category: "released", type: "Sortie", date_h: 6, date_label: "il y a 6h", title: "Chainsaw Man Saison 2 épisode 1 — le retour du 2D traditionnel", summary: "Animation redessinée à la main, nouveau réalisateur (Tatsuya Yoshihara ex-Bleach), arc Academy lancé dès ep1. MAL 9.4 après 12h. Pré-génériques d'ouverture signés Ado.", tags: ["#mappa", "#chainsawman", "#anime"], unread: true, starred: true, icon: "star" },
    { id: "a2", actor: "HBO", category: "upcoming", type: "Production", date_h: 3, date_label: "il y a 3h", title: "The Last of Us Saison 3 commence à tourner — Seattle en mai", summary: "Pedro Pascal de retour, Kaitlyn Dever confirmée dans Abby. Showrunners Mazin + Druckmann toujours au scénario. Sortie prévue début 2027.", tags: ["#hbo", "#tlou", "#serie"], unread: true, starred: true, icon: "sparkles" },
    { id: "a3", actor: "A24", category: "upcoming", type: "Annonce", date_h: 24, date_label: "hier", title: "Ari Aster prépare un thriller sci-fi avec Joaquin Phoenix", summary: "Après Eddington, Aster pivote vers la science-fiction. Budget 80M$, tournage été. Phoenix dans le rôle principal pour la 3e fois avec Aster.", tags: ["#a24", "#ariaster", "#cinema"], unread: true, starred: true, icon: "flag" },
    { id: "a4", actor: "Netflix", category: "released", type: "Finale", date_h: 8, date_label: "il y a 8h", title: "Squid Game saison 3 — la fin divise, 180M vues en 3 jours", summary: "Hwang Dong-hyuk signe la fin de la série. Réception polarisée : les fans apprécient le bouclage, les critiques pointent un finale trop politique. Spin-off US confirmé.", tags: ["#netflix", "#squidgame", "#serie"], unread: true, starred: false, icon: "alert" },
    { id: "a5", actor: "Studio Ghibli", category: "upcoming", type: "Annonce", date_h: 96, date_label: "il y a 4j", title: "Miyazaki annonce un nouveau film — sortie 2028", summary: "Via Toshio Suzuki en interview NHK. Production déjà lancée avec une équipe rajeunie. Thème : relations intergénérationnelles. Titre pas encore dévoilé.", tags: ["#ghibli", "#miyazaki", "#anime"], unread: true, starred: true, icon: "star" },
    { id: "a6", actor: "Kyoto Animation", category: "released", type: "Film", date_h: 120, date_label: "il y a 5j", title: "Violet Evergarden : Le film final arrive en octobre", summary: "KyoAni ferme la franchise avec un long-métrage. Sortie Japon octobre, international janvier 2027. Premier trailer dévoilé.", tags: ["#kyoani", "#violetevergarden", "#anime"], unread: true, starred: false, icon: "sparkles" },
    { id: "a7", actor: "MAPPA", category: "upcoming", type: "Production", date_h: 72, date_label: "il y a 3j", title: "Jujutsu Kaisen : MAPPA confirme le film Shibuya alternatif", summary: "Adaptation cinéma de l'arc Shibuya avec scènes inédites. Sortie 2027. Stratégie Gege Akutami pour clore proprement la saga anime.", tags: ["#mappa", "#jjk", "#film"], unread: false, starred: false, icon: "paper" },
    { id: "a8", actor: "HBO", category: "industry", type: "Série", date_h: 48, date_label: "il y a 2j", title: "House of the Dragon S3 reporté à 2027", summary: "Budget explose, showrunner demande plus de temps. GoT spin-off 'A Knight of the Seven Kingdoms' sort en compensation cet automne.", tags: ["#hbo", "#got", "#hotd"], unread: false, starred: false, icon: "alert" },
    { id: "a9", actor: "A24", category: "released", type: "Sortie", date_h: 144, date_label: "il y a 6j", title: "A24 sort Tuesday, thriller psychologique qui divise Cannes", summary: "Première à Cannes standing ovation de 8 min. Les critiques américaines beaucoup plus mitigées. Sortie salles juin, streaming août.", tags: ["#a24", "#cannes", "#cinema"], unread: false, starred: false, icon: "check" },
    { id: "a10", actor: "Netflix", category: "upcoming", type: "Lancement", date_h: 168, date_label: "il y a 7j", title: "Arcane saison finale — Netflix confirme une suite dans l'univers", summary: "Après la fin d'Arcane, Riot + Netflix annoncent Noxus : série ambiance Rome/Sparte. Showrunner Christian Linke toujours impliqué.", tags: ["#netflix", "#arcane", "#riot"], unread: false, starred: true, icon: "sparkles" },
    { id: "a11", actor: "MAPPA", category: "industry", type: "Interview", date_h: 192, date_label: "il y a 8j", title: "Interview Manabu Otsuka : comment MAPPA gère la crise du burnout", summary: "PDG MAPPA parle des conditions de travail. Nouvelles règles : max 2 productions en parallèle, budgets +20%, équipes +30%. Réponse aux polémiques 2024.", tags: ["#mappa", "#interview", "#industrie"], unread: false, starred: false, icon: "paper" },
    { id: "a12", actor: "Studio Ghibli", category: "released", type: "Re-release", date_h: 240, date_label: "il y a 10j", title: "Princesse Mononoké : projection IMAX mondiale en mai", summary: "Pour les 30 ans du film. Scan 4K remasterisé supervisé par Ghibli. 500 salles dont Grand Rex à Paris.", tags: ["#ghibli", "#mononoke", "#imax"], unread: false, starred: false, icon: "star" },
  ],

  prod_cases: [
    { company: "Dune : Part Three", logo_mark: "D3", color: "#b8824a", scale: "Denis Villeneuve · 200M$ budget", model: "Warner Bros", domain: "Cinéma SF", when: "Décembre 2026", headline: "Tournage en cours au Maroc. Adaptation de Dune Messiah. Zendaya, Chalamet, Florence Pugh confirmés.", impact: "Événement cinéma 2026" },
    { company: "One Piece Netflix S2", logo_mark: "OP", color: "#e60012", scale: "Netflix · live-action", model: "Adaptation manga", domain: "Série", when: "Septembre 2026", headline: "Arc Baroque Works. Nouveaux castings : Crocodile par Joe Manganiello. 8 épisodes.", impact: "Deuxième saison la plus attendue" },
    { company: "Avatar 3 : Fire and Ash", logo_mark: "AV", color: "#3a8f9c", scale: "James Cameron · 350M$", model: "Disney/20th", domain: "Cinéma SF", when: "Décembre 2026", headline: "Peuple du feu introduit. 3h10 de film. Villain principal : Varang joué par Oona Chaplin.", impact: "Potentiel record box-office" },
  ],

  trends: [
    {
      id: "tan-adaptations",
      label: "Adaptations live-action de manga",
      kicker: "Tendance production",
      momentum: "+220% · 90j",
      pulse: [2, 3, 4, 5, 7, 9, 12, 14],
      articles_count: 10,
      summary: "One Piece Netflix, Ranma 1/2, YuYu Hakusho, Sakamoto Days en prod. Netflix domine avec Shōgun + licensing aggressif. Qualité inégale mais traction forte.",
      actors_involved: ["Netflix", "Toho", "Shueisha"],
      status: "rising",
    },
    {
      id: "tan-hbo-return",
      label: "HBO retrouve sa hype prestige",
      kicker: "Tendance streaming",
      momentum: "+140% · 60j",
      pulse: [1, 2, 3, 4, 5, 7, 9, 10],
      articles_count: 8,
      summary: "The Last of Us S2, White Lotus S3, Succession spin-off, Euphoria S3 : HBO aligne 4 phénomènes consécutifs. Max récupère abonnés perdus.",
      actors_involved: ["HBO", "Max", "A24"],
      status: "rising",
    },
    {
      id: "tan-mangaka-oldies",
      label: "Retour des vieux mangakas",
      kicker: "Tendance édition",
      momentum: "+75% · 90j",
      pulse: [1, 1, 2, 2, 3, 3, 4, 5],
      articles_count: 6,
      summary: "Rumiko Takahashi revient avec MAO, Miyazaki annonce un film, Hirohiko Araki accélère JoJo Part 9. Génération 60-70s toujours productive.",
      actors_involved: ["Shōgakukan", "Shueisha", "Ghibli"],
      status: "stable",
    },
    {
      id: "tan-ai-animation",
      label: "IA dans l'animation — tension",
      kicker: "Controverse industrie",
      momentum: "+195% · 60j",
      pulse: [1, 2, 3, 3, 5, 7, 9, 11],
      articles_count: 7,
      summary: "Toei teste IA pour intercalages. Grève animateurs Corée. Guilde japonaise publie guidelines. Miyazaki critique publiquement. Débat générationnel.",
      actors_involved: ["Toei", "MAPPA", "Netflix", "Toho"],
      status: "debated",
    },
  ],
};
